"""text migration

Revision ID: 37eb7958c3fd
Revises: b94b5b874157
Create Date: 2023-02-22 14:44:38.836845

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision = '37eb7958c3fd'
down_revision = 'b94b5b874157'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('universities_data', sa.Column('uniRankId', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('universities_data', 'uniRankId')
    # ### end Alembic commands ###
