"""test

Revision ID: 861b49dbd458
Revises: 
Create Date: 2023-03-07 12:56:26.222053

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '861b49dbd458'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('universities_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('acronym', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('founded', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('motto', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ranking', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('colors', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('logo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('controlType', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('entityType', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('uniRankId', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tel', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fax', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('universities_data')
    # ### end Alembic commands ###
