"""text migration

Revision ID: b94b5b874157
Revises: 5e7872115c0c
Create Date: 2023-02-22 14:19:21.195299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b94b5b874157'
down_revision = '5e7872115c0c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('universities_data', sa.Column('profit', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('universities_data', 'profit')
    # ### end Alembic commands ###
